### ISSUE TITLE
Scanning Window Size Issue

### ISSUE THREAD

**Issue by isaacbdawson** [wildabeast/BarcodeScanner#130]
The scan window on the galaxy s5 is just ridiculous.
Any ideas how to fix this?

![screenshot_2014-07-29-14-47-58](https://cloud.githubusercontent.com/assets/8303885/3742605/85f65e26-176b-11e4-832a-ebde672e23a3.jpg)

**Comment by jrameriz** [comment]
they have been increased but not for phonegap build plugin

**Comment by jrameriz** [comment]
I've changed CameraManager.java to:
private static final int MIN_FRAME_WIDTH = 480;
private static final int MIN_FRAME_HEIGHT = 480;
private static final int MAX_FRAME_WIDTH = 1000;
private static final int MAX_FRAME_HEIGHT = 750;
after i go and use the run command locally on android device but the window is still small. any ideas?

**Comment by radumvlad** [comment]
i think you need to rebuild the android library after changing this values

it would be nice to control this values from PhoneGap :)

**Comment by 48design** [comment]
It would be realy nice if it were possible to set this via an option in the config.xml when building with PhoneGap Build. We don't use the CLI at the moment, so we're not able to modify and recompile the library.

**Comment by jrameriz** [comment]
@radumvlad I deleted the the android library than ran it! and nothing changed! 
@48 design I'm in the same boat, frustration!

**Comment by heberfabiano** [comment]
Guys, too late for a question?

I tried the solution that @isaacbdawson provided but I'm getting Multiple dex files error when trying to run "ionic build android".

    [dx] UNEXPECTED TOP-LEVEL EXCEPTION:
       [dx] com.android.dex.DexException: Multiple dex files define Lcom/squareup/okhttp/Address;
       [dx]     at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
       [dx]     at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
       [dx]     at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
       [dx]     at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
       [dx]     at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
       [dx]     at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
       [dx]     at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
       [dx]     at com.android.dx.command.dexer.Main.run(Main.java:246)
       [dx]     at com.android.dx.command.dexer.Main.main(Main.java:215)

Any idea about what I'm doing wrong?

Thank you!

**Comment by phpprousa** [comment]
For those of us creating an HTML5 app, then wrapping with PhoneGap build, any easy way to add this support for larger scan windows?

**Comment by bapatel1** [comment]
You can include .jar file which I have created with bigger viewfinder area. 
https://github.com/bapatel1/zxing-barcode-scanner-bigger-viewfinder

**Comment by eramirez1983** [comment]
I change the size from CameraManager.java and later I cleaned both proyects and I found a problem with the size of the screen, I Just wanna take all size, but when I'm testing I found which I put the cellphone on landscape take the correct size but if I put to the horizontal position not work correctly, this is because take the size of the screen before to invoke camera scanner, I made a little change like this...

		Display display = getWindowManager().getDefaultDisplay();
		Point size = new Point();
		display.getSize(size);
		int width = size.x;
		int height = size.y;
			
		// go to fullscreen scan
		Intent intent = new Intent("com.google.zxing.client.android.SCAN");
		intent.putExtra("SCAN_WIDTH", height);
		intent.putExtra("SCAN_HEIGHT", width);
		intent.putExtra("PROMPT_MESSAGE", "Enfoque un código de barras en el interior del el lector para escanearlo.");
		intent.putExtra("SCAN_MODE", "ONE_D_MODE");//ONE_D_MODE
		startActivityForResult(intent, SCANNER_REQUEST_CODE);

I  only invert the values of width and height, I made this because this is real size if you want take all size from the screen, when you invoke scanner always starts on landscape position, I hope this helps, regards.
