### ISSUE TITLE
Not working on windows 8

### ISSUE THREAD

**Issue by Ringelpietz** [wildabeast/BarcodeScanner#143]
Hi,

I'm trying to execute your BarcodeScanner on my Windows 8 Tablet (Micrososft Surface Win8) and I'm not able to do it to work. The camera is launched and open but it seems that it is not scanning. No appears any figure or area where scan functionality is active.

I implemented the code and added the plugin to my cordova project as you say in your readme file

Any idea about what am I doing wrong?.
BTW : any other platforms (android,ios) works well with this plugin

Thank you for your help :)

**Comment by venki0552** [comment]
Got same issue The led next to the camera is on but not camera no scanning area only the LED is on
