### ISSUE TITLE
Cancel Button not working in Iphone4s ios8

### ISSUE THREAD

**Issue by DynamicLeo** [wildabeast/BarcodeScanner#162]
when i push the cancel button , it doesn't work until it scan a barcode

**Comment by Marshall-L-D** [comment]
I manually applied the changes proposed by @peterfox1 and it seems to have fixed the issue on my iPad2 under iOS 8.1.1.  Why does everyone seem to be forking this project? Can't a committer get this patch applied to the plugin that you get from the Cordova plug registry for "com.phonegap.plugins.barcodescanner" ?

**Comment by ascendedmasta** [comment]
This problem just showed up for me overnight....not sure what the problem is. I tried @peterfox1 method and it worked...only now when it gets a barcode the app crashes.... What's going on?

**Comment by hoangquang** [comment]
@twomz - that's so great, it's working good now.

**Comment by dkoding** [comment]
wildabeast, where are you? Please fix this in the main barcodescanner in Cordova.

**Comment by karsunke** [comment]
Had the same problem. I used the fork https://github.com/andwaal/BarcodeScanner and it worked fine.

**Comment by hoangquang** [comment]
You guys can check out the message of @peterfox1 above
