### ISSUE TITLE
iOS 8 - cancel button not working on iPhone 4S - issues with zoom

### ISSUE THREAD

**Issue by felarov** [wildabeast/BarcodeScanner#185]
I installed a cordova app on iOS 8 with the plugin installed. The plugin starts up perfectly, but the cancel button does not function. The camera does also not seem to adjust the "zoom" to focus the barcode. The same app works well on Android

**Comment by ascendedmasta** [comment]
Same problem...Can't zoom to see finer lines of 7 Digit Code 39 Barcode...Is there any type of fix to this?

**Comment by mariusmarais** [comment]
See #162, #167 for fixes

**Comment by wildabeast** [comment]
Fixed by #167.
