### ISSUE TITLE
Duplicate registration for activity com.google.zxing.client.android.CaptureActivity

### ISSUE THREAD

**Issue by mirko77** [wildabeast/BarcodeScanner#229]
Every time I run `cordova prepare` I get an error in my AndroidManifest.xml:

`Duplicate registration for activity com.google.zxing.client.android.CaptureActivity`

I remove the duplicated activity on the manifest and everything works fine again.

I tried to remove and to re-add the plugin but it happens anyway each time I do a `cordova prepare`

Any suggestion?

**Comment by mirko77** [comment]
I solved it adding and removing it again, and manually deleting the extra entry in the manifest

**Comment by pke** [comment]
How *exactly* did you solve that? Step by step please, this is driving me crazy. It just started to happen.
Removing adding the plugin did not help. Removing the platform did not help.
