### ISSUE TITLE
Windows - JavaScript runtime error: Class not registered

### ISSUE THREAD

**Issue by luissilvaos** [wildabeast/BarcodeScanner#231]
Hi,
I'm building an app for Windows 8 and Windows Phone 8 with phonegap and when I try to use this plugin (BarcodeScanner) it allways shows a popup error with the following message: 

Exception is about to be caught by JavaScript library code at line 74, column 13 in ms-appx://myapp.windows/www/plugins/com.phonegap.plugins.barcodescanner/src/windows8/BarcodeScannerProxy.js

0x80040154 - JavaScript runtime error: Class not registered

Can you help me with this?
Cheers

**Comment by luissilvaos** [comment]
Problem solved.
Just for the record, when using Visual Studio Pro 2013 - Update 4, we have to manually add WinRT class to the AppxManifest file.

Something like this:

```xml
<Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
		<ActivatableClass ActivatableClassId="WinRTBarcodeReader.Reader" ThreadingModel="both" />
      </InProcessServer>
</Extension>
```

**Comment by mlafleur** [comment]
The example is missing the Path node which will cause the compile to fail. Use the following instead:

```xml
<Extensions>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>CLRHost.dll</Path>
        <ActivatableClass ActivatableClassId="WinRTBarcodeReader.Reader" ThreadingModel="both" />
      </InProcessServer>
    </Extension>
  </Extensions>
```
