### ISSUE TITLE
Cancel button does not work on IOS 8

### ISSUE THREAD

**Issue by dkoding** [wildabeast/BarcodeScanner#237]
Please fix it.

There are several solutions to the problem online and even a pull request adressing the issue. 
So please apply the fix, this problem is ruining the plugin for a lot of apps out there.

**Comment by cfh463** [comment]
+1 having the same issue - what is the pull request?

**Comment by ascendedmasta** [comment]
I had to manually add in the fix. Works...for now.

**Comment by SingleID** [comment]
please fix it :-/

**Comment by michaelhogg** [comment]
@cfh463 #167 fixes the issue, using [this commit by basvanbeek](https://github.com/basvanbeek/BarcodeScanner/commit/b571e2be99334eb4d68f3ab01d1a693bd8e2e20a).

**Comment by hafeyang** [comment]
+1 have this issue....

**Comment by dfabreguette-ap** [comment]
+1

**Comment by wildabeast** [comment]
Fixed by #167.
