### ISSUE TITLE
Scanner (camera) freeze

### ISSUE THREAD

**Issue by askbar** [wildabeast/BarcodeScanner#284]
Hi 

I've installed the scanner and every time I fire it up, on my iphone 6, it freezes. If I flip between back and front camera the scanner/camera works fine again. If I close the scanner/camera (still in my app) and activate it again, its frozen til I toggle front/back camera.

Any ideas ?

**Comment by wodka** [comment]
I have the same issue - have you found anything yet?

**Comment by askbar** [comment]
Hi

Did'nt really nail the problem, installed one of the demo projects and it worked fine - so I copied the js and that works. I'm not sure if the way the scanner is loaded makes a difference, this works for me:
```var scanner = cordova.require("cordova/plugin/BarcodeScanner");
scanner.scan(function (result) {
	...
}, function (error) { 
	...
});```

**Comment by wodka** [comment]
:/ sadly didn't solve the problem, thx anyway!

**Comment by ivanets** [comment]
I got a same problem, and can't find how to resolve it.
Have you, guys, found anything? Thx.

**Comment by askbar** [comment]
Hi
Did you try my code above ? I haven't got any better suggestions

**Comment by wodka** [comment]
I tried your code, no change...

I can unfreeze the scanner by switching between front and backcamera -> but then I require this fix to receive results: https://github.com/wildabeast/BarcodeScanner/issues/282

**Comment by wodka** [comment]
By now I have a solution:

one file needs to be modified:
AppDelegate.m
```(objectivec)
    // replace line 88 "self.window.rootViewController = self.viewController;"
    UINavigationController *aNavigationController = [[UINavigationController alloc]                                                  initWithRootViewController:self.viewController];
    self.window.rootViewController = aNavigationController;
```
(source: http://stackoverflow.com/questions/12350437/getting-current-uiviewcontroller-in-phonegap)

-> change will be that the right view is taken :)

you should also apply fix https://github.com/wildabeast/BarcodeScanner/issues/282

**Comment by askbar** [comment]
awsome  :+1:  I'm not really into xcode and that native app part - so I hope your fix will go into the source of the project !?
