### ISSUE TITLE
Call to unknown plugin: BarcodeScanner

### ISSUE THREAD

**Issue by lborie** [wildabeast/BarcodeScanner#32]
Hi,

With the help of Eccenux I was able to install the plugin and to build an APK.
But when I deploy and I launch the scan, I have an error : 
Scanning failed: Class not found.

And when I open DDMS, I have the following problem : 
"exec() call to unknown plugin barcodescanner"

Is it a problem of dependencies of the plugin ?

**Comment by jls14** [comment]
I have tried to do all the changes and this plugin is still giving me issues.  Did anything change with the latest release.  

I have done a plugin install on the wildabeast and jonathannaguin gits of the source, and still not getting anywhere. still get Uncaught module com.phonegap.plugins.barcodescanner.barcodescanner not found.  

I have installed via plugman and phonegap CLI. 

I am using the latest phonegap. do I need to just roll back to an earlier version or has someone got this to work on phonegap 4.2?
