### ISSUE TITLE
Trying to add a back button in android.

### ISSUE THREAD

**Issue by vikassingla** [wildabeast/BarcodeScanner#350]
Hello , I am trying to add a button in android . I have changed the layout , created a button for it . But whenever I am adding in CaptureActivity.java ,  it is not working as expected. Can you help me with it.

**Comment by AbhishekShukla1289** [comment]
I added this piece of code in CaptureActivity.java while adding a button in the layout/capture.xml referring to that button:

Button button = (Button) findViewById(fakeR.getId("id", "button3"));
button.setOnClickListener(new View.OnClickListener() {
    public void onClick(View v) {
        finish();
    }
});
