### ISSUE TITLE
German text encoding issue while scanning qr code

### ISSUE THREAD

**Issue by sanny16** [wildabeast/BarcodeScanner#355]
DON'T POST ISSUES HERE, GO TO https://github.com/phonegap-plugin-barcodescanner/issues  <-- This url leads to 404 error.

Hi,

I am using bar code scanner in an sap ui5 application, and during debugging i found out that in the result of barcode plugin proper german text was not being captured properly whereas if i just mention static german text in application it is being properly displayed. For example: "gesägt" (actual german text in qr code) is getting converted into "gesÃ¤gt"  (after scanning qr code via plugin).

I am using google chrome to test application on desktop. Static german text is being displayed properly on browser if i hard code it in the application.

I have already included this "<meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>" in index.html file of application so it handles static data display. As of now this app is being used locally ,so no server call is going.

What can be the problem for this issue?
Please post your suggestions.

Thanks,
Sanny.

**Comment by wildabeast** [comment]
updated that bad link. use https://github.com/phonegap/phonegap-plugin-barcodescanner/issues.

If you're using the code in this repository, its extremely out of date.
