### ISSUE TITLE
Modifying the overlay style

### ISSUE THREAD

**Issue by guizmo** [wildabeast/BarcodeScanner#39]
Hi there is there anyway to change the style , button text , element position of the overlay ?

**Comment by prasobhk** [comment]
@guizmo , is it possible to show barcodescanner inside a div rather than showing entire screen? Thanks

**Comment by dchahla** [comment]
dang @guizmo you went in on that.

**Comment by guizmo** [comment]
nope i did not manage to

**Comment by dchahla** [comment]
Regardless of if you did or did not closed a PR - the amount of research and thought you provided for others is admirable. I'd like to think I do a lot of tech. I applaud you.
