### ISSUE TITLE
Nexus 7 / Android 4.1: "the Android camera encountered a problem"

### ISSUE THREAD

**Issue by FelixSchwarz** [wildabeast/BarcodeScanner#4]
This is a clone of https://github.com/phonegap/phonegap-plugins/issues/866 as I figure that issues should be filed now.

> I have installed the Barcode Scanner Phonegap plugin.
> It works very well except for my nexus 7 tablet with this error message :
> "Sorry, the Android camera encountered a problem. You may need to restart the device."
> 
> I have restarted, but I have still the same problem.
> 
> Here is my error message in the logcat console
> 
> ```
> 11-05 11:36:50.197: W/CaptureActivity(5517): java.io.IOException
> 11-05 11:36:50.197: W/CaptureActivity(5517): at com.google.zxing.client.android.camera.CameraManager.openDriver(CameraManager.java:128)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at com.google.zxing.client.android.CaptureActivity.initCamera(CaptureActivity.java:606)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at com.google.zxing.client.android.CaptureActivity.surfaceCreated(CaptureActivity.java:346)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at android.view.SurfaceView.updateWindow(SurfaceView.java:543)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at android.view.SurfaceView.access$000(SurfaceView.java:81)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:169)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:671)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1820)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4214)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at android.view.Choreographer.doCallbacks(Choreographer.java:555)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at android.view.Choreographer.doFrame(Choreographer.java:525)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at android.os.Handler.handleCallback(Handler.java:615)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at android.os.Handler.dispatchMessage(Handler.java:92)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at android.os.Looper.loop(Looper.java:137)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at android.app.ActivityThread.main(ActivityThread.java:4745)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at java.lang.reflect.Method.invokeNative(Native Method)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at java.lang.reflect.Method.invoke(Method.java:511)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
> 11-05 11:36:50.197: W/CaptureActivity(5517): at dalvik.system.NativeStart.main(Native Method)
> ```
> 
> What should I do ?
> 
> Thanks for your answer.

Just to add: I'm seeing the exactly same issue. I suspect an upgrade to the latest zxing version fixes the problem as indicated in the pull request https://github.com/phonegap/phonegap-plugins/pull/654

**Comment by drmpf** [comment]
I got the same problem Fixed it with

SurfaceHolder surfaceHolder = surfaceView.getHolder();
surfaceHolder.setType(SurfaceHolder.SURFACE_TYPE_PUSH_BUFFERS);

Note: this seems to be a recent issue with the OS ( pre V3.0 Android) as the code was previously working.

**Comment by athkalia** [comment]
I had a related problem and it turned out I was missing the Marhmellow runtime permission for camera
