### ISSUE TITLE
Question how to install this plugin to make it work with my phonegap android app

### ISSUE THREAD

**Issue by greenlaw110** [wildabeast/BarcodeScanner#47]
Sorry for the question but I am an new comer to Android phonegap app development. Can you add a manual on how to install this plugin to make it work with my app? 

My phonegap version is 3.0.0-0.14.4, cordova version is 3.0.9

**Comment by jahny4** [comment]
i am getting same error

barcodescanner.js:130 Uncaught ReferenceError: require is not defined

ionic.bundle.js:20306 ReferenceError: cordova is not defined

----------------------
Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.8.11
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.3
Ionic App Lib Version: 0.0.19
ios-deploy version: Not installed
ios-sim version: 3.1.1 
OS: Mac OS X Mavericks
Node Version: v0.12.2
Xcode version: Xcode 6.1.1 Build version 6A2008a 


my index.html
------------------------
    
    <script src="lib/ionic/js/ionic.bundle.js"></script>


    <script src="js/ng-cordova.min.js"></script>
    <script src="js/ng-cordova-mocks.min.js"></script>
    <script src="js/barcodescanner.js"></script>

    
    <script src="cordova.js"></script>

    
    <script src="js/app.js"></script>
    <script src="js/controllers.js"></script>


--------------------------------
 <button class="button" ng-click="scanBarcode()">scan</button>
---------------------------------

------app.js-----------------
angular.module('starter', ['ionic', 'starter.controllers', 'ngCordova'])


------controllers.js-------------------
angular.module('starter.controllers', ['ngCordova'])

.controller('AppCtrl', function($scope, $ionicModal, $timeout, $stateParams, $http, $cordovaBarcodeScanner) {

.......

$scope.scanBarcode = function() {
    var scanner = cordova.plugins.BarcodeScanner;
    if (scanner == undefined) {
        scanner = cordova.require("cordova/plugin/BarcodeScanner");
    }

    scanner.scan() 
            .then(function (imageData) { 
                    alert(imageData.text);
                    console.log(imageData.format); 
                    // Success! Barcode data is here 
                 }, function (err) { 
                     console.log(err); 
                     // An error occurred 
                 }); 
        };


----------------------------------------------
Any help is appreciated.
