### ISSUE TITLE
Unable to compile zxing-all-in-one

### ISSUE THREAD

**Issue by satheeshwaran** [wildabeast/BarcodeScanner#65]
Getting this error when I compile,

 "zxing::DecodeHints::addFormat(zxing::BarcodeFormat)", referenced from:
      -[PGbcsProcessor captureOutput:didOutputSampleBuffer:fromConnection:] in PGBarcodeScanner.o
  "zxing::DecodeHints::DecodeHints()", referenced from:
      -[PGbcsProcessor captureOutput:didOutputSampleBuffer:fromConnection:] in PGBarcodeScanner.o
  "zxing::BinaryBitmap::BinaryBitmap(zxing::Refzxing::Binarizer)", referenced from:
      -[PGbcsProcessor captureOutput:didOutputSampleBuffer:fromConnection:] in PGBarcodeScanner.o
  "zxing::HybridBinarizer::HybridBinarizer(zxing::Refzxing::LuminanceSource)", referenced from:
      -[PGbcsProcessor captureOutput:didOutputSampleBuffer:fromConnection:] in PGBarcodeScanner.o
  "zxing::ReaderException::ReaderException(char const_)", referenced from:
      -[PGbcsProcessor getLuminanceSourceFromSample:imageBytes:] in PGBarcodeScanner.o
  "zxing::MultiFormatReader::MultiFormatReader()", referenced from:
      -[PGbcsProcessor captureOutput:didOutputSampleBuffer:fromConnection:] in PGBarcodeScanner.o
  "zxing::GreyscaleLuminanceSource::GreyscaleLuminanceSource(unsigned char_, int, int, int, int, int, int)", referenced from:
      -[PGbcsProcessor getLuminanceSourceFromSample:imageBytes:] in PGBarcodeScanner.o
  "zxing::Result::getText()", referenced from:
      -[PGbcsProcessor captureOutput:didOutputSampleBuffer:fromConnection:] in PGBarcodeScanner.o
  "zxing::Result::getBarcodeFormat() const", referenced from:
      -[PGbcsProcessor captureOutput:didOutputSampleBuffer:fromConnection:] in PGBarcodeScanner.o
  "zxing::String::getText() const", referenced from:
      -[PGbcsProcessor captureOutput:didOutputSampleBuffer:fromConnection:] in PGBarcodeScanner.o
  "typeinfo for zxing::ReaderException", referenced from:
      typeinfo for zxing::ReaderException\* in PGBarcodeScanner.o
      GCC_except_table15 in PGBarcodeScanner.o
  "typeinfo for zxing::IllegalArgumentException", referenced from:

Any framework that I should add or what?

**Comment by mobileComputingNITH** [comment]
I am also getting this error. Why was it close? Is there a solution for it? @wildabeast
