### ISSUE TITLE
Fail right after installation

### ISSUE THREAD

**Issue by Pab89** [wildabeast/BarcodeScanner#67]
Hi there
I tryed to install your barcodescanner. All that happends is the following.

First i do:
cordova build(Works fine)

then i install barcodescanner via terminal:
cordova plugin add https://github.com/wildabeast/BarcodeScanner

Then
cordova build(Fails se errors msg below)
The following build commands failed:
    Check dependencies
(1 failure)
*\* BUILD FAILED **

The following build commands failed:
    CompileXIB vvs/Resources/scannerOverlay.xib
(1 failure)

What am i doing wrong? Tryed alot of things now nothing works removed and readded it tons of times with no effect.

**Comment by minustime** [comment]
@DanielAron solution worked for me. Thanks!

**Comment by Yagger** [comment]
@DanielAron solution worked for me too. Thanks!
